export const PH_REGIONS = [
    { code: "NCR", name: "National Capital Region (NCR)" },
    { code: "CAR", name: "Cordillera Administrative Region (CAR)" },
    { code: "I", name: "Region I — Ilocos Region" },
    { code: "II", name: "Region II — Cagayan Valley" },
    { code: "III", name: "Region III — Central Luzon" },
    { code: "IV-A", name: "Region IV-A — CALABARZON" },
    { code: "IV-B", name: "Region IV-B — MIMAROPA" },
    { code: "V", name: "Region V — Bicol Region" },
    { code: "VI", name: "Region VI — Western Visayas" },
    { code: "VII", name: "Region VII — Central Visayas" },
    { code: "VIII", name: "Region VIII — Eastern Visayas" },
    { code: "IX", name: "Region IX — Zamboanga Peninsula" },
    { code: "X", name: "Region X — Northern Mindanao" },
    { code: "XI", name: "Region XI — Davao Region" },
    { code: "XII", name: "Region XII — SOCCSKSARGEN" },
    { code: "XIII", name: "Region XIII — Caraga" },
    { code: "BARMM", name: "Bangsamoro Autonomous Region (BARMM)" },
];

export const PH_PROVINCES: Record<string, string[]> = {
    "NCR": ["Metro Manila"],
    "CAR": ["Abra", "Apayao", "Benguet", "Ifugao", "Kalinga", "Mountain Province"],
    "I": ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"],
    "II": ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"],
    "III": ["Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales"],
    "IV-A": ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"],
    "IV-B": ["Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon"],
    "V": ["Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon"],
    "VI": ["Aklan", "Antique", "Capiz", "Guimaras", "Iloilo", "Negros Occidental"],
    "VII": ["Bohol", "Cebu", "Negros Oriental", "Siquijor"],
    "VIII": ["Biliran", "Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte"],
    "IX": ["Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay"],
    "X": ["Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental"],
    "XI": ["Davao de Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental"],
    "XII": ["Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat"],
    "XIII": ["Agusan del Norte", "Agusan del Sur", "Dinagat Islands", "Surigao del Norte", "Surigao del Sur"],
    "BARMM": ["Basilan", "Lanao del Sur", "Maguindanao", "Sulu", "Tawi-Tawi"],
};
